### PR TITLE
Give ability to set outline and stroke width in setProperties.

### PR DESCRIPTION
**Pull request by ravishivt**
Added new options to setProperties for setting the lineWidth for
various states: outline_width, stroke_width, hi_outline_width, and
hi_stroke_width.

Added hi_outline option to setProperties which adjusts the color of the
highlighted outline.

Changed parsing of properties in setProperties to allow false values.
This allows the user to disable the outline or stroke altogether.  I
personally disable stroke and make the outline lineWidth larger to give
a cleaner look.

Use lineJoin = “round” so the rectangle edges are slightly rounded.
They are more pronounced if the line widths are set high.

Changed math of creating the rectangles so it accounts for the user
adjust lineWidth properties.  Outline and stroke are now always
rendered inside the selection instead of straddling it.

### CODE REVIEW

**Comment by rsimon** [comment]
Great addition - many thanks!

**Comment by rsimon** [comment]
Just realized a small issue: when I create an annotation now, the box "shrinks" a little, i.e. the size of the selection box now differs a little from the size of the annotation that get's drawn by the viewer. (Just tried this with the default style settings.) Could it be that there's still is a minor (+/-1 pixel) issue with the new size calculation code?

Cheers,
R

**Comment by ravishivt** [comment]
Good find.  I took a quick look and did find that the rectangle dimensions are off by 1 between the selection box and the annotation box.  I'm not sure if the rectangle drawing methods should accommodate for that difference or the source of the dimensions difference should be patched.  I'll have take a deeper look when I get some time.

**Comment by ravishivt** [comment]
Should be fixed.  Check out #99.

**Pull request merged**
